### ISSUE TITLE
memtier: fix benchmark.py

### ISSUE THREAD

**Issue by carverdamien** [carverdamien/acdc#23]
['memtier_benchmark', '-s', 'redisa', '-d', '4096', '--key-pattern=R:R', '--key-maximum=379682', '--ratio=1:10', '-c', '1', '-t', '1', '--test-time', '300']
Traceback (most recent call last):
  File "benchmark.py", line 58, in <module>
    main()
  File "benchmark.py", line 56, in main
    run(args)
  File "benchmark.py", line 32, in run
    callback(res.named)
  File "benchmark.py", line 22, in callback
    client.write_points([p for p in influxformat(measurement, fields, tags=tags)])
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 468, in write_points
    tags=tags, protocol=protocol)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 532, in _write_points
    protocol=protocol
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 312, in write
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 271, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=97329233.0,avglat=0.04,avgopsps=23514.0,bw=0.0,lat=nan,ops=3315757.0,opsps=0.0,threads=1.0 1511775052000000000': invalid number"}

**Comment by carverdamien** [comment]
['memtier_benchmark', '-s', 'redisa', '-d', '4096', '--key-pattern=R:R', '--key-maximum=379682', '--ratio=1:10', '-c', '1', '-t', '1', '--test-time', '300']
[RUN #1 46%, 137 secs] 1511775997 timestamp:  1 threads:     3258462 ops,       0 (avg:   23782) ops/sec, 0/sec (avg: 98439879/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3258462', 'avgbw': '98439879', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  23782', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=98439879.0,avglat=0.04,avgopsps=23782.0,bw=0.0,lat=nan,ops=3258462.0,opsps=0.0,threads=1.0 1511775997000000000': invalid number"}

[RUN #1 46%, 138 secs] 1511775998 timestamp:  1 threads:     3258462 ops,       0 (avg:   23610) ops/sec, 0/sec (avg: 97726543/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3258462', 'avgbw': '97726543', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  23610', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=97726543.0,avglat=0.04,avgopsps=23610.0,bw=0.0,lat=nan,ops=3258462.0,opsps=0.0,threads=1.0 1511775998000000000': invalid number"}

[RUN #1 46%, 139 secs] 1511775999 timestamp:  1 threads:     3258462 ops,       0 (avg:   23440) ops/sec, 0/sec (avg: 97023460/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3258462', 'avgbw': '97023460', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  23440', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=97023460.0,avglat=0.04,avgopsps=23440.0,bw=0.0,lat=nan,ops=3258462.0,opsps=0.0,threads=1.0 1511775999000000000': invalid number"}

[RUN #1 47%, 140 secs] 1511776000 timestamp:  1 threads:     3258462 ops,       0 (avg:   23272) ops/sec, 0/sec (avg: 96330432/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3258462', 'avgbw': '96330432', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  23272', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=96330432.0,avglat=0.04,avgopsps=23272.0,bw=0.0,lat=nan,ops=3258462.0,opsps=0.0,threads=1.0 1511776000000000000': invalid number"}

[RUN #1 47%, 141 secs] 1511776001 timestamp:  1 threads:     3258462 ops,       0 (avg:   23107) ops/sec, 0/sec (avg: 95647224/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3258462', 'avgbw': '95647224', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  23107', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=95647224.0,avglat=0.04,avgopsps=23107.0,bw=0.0,lat=nan,ops=3258462.0,opsps=0.0,threads=1.0 1511776001000000000': invalid number"}

[RUN #1 47%, 142 secs] 1511776002 timestamp:  1 threads:     3258462 ops,       0 (avg:   22945) ops/sec, 0/sec (avg: 94973649/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3258462', 'avgbw': '94973649', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  22945', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=94973649.0,avglat=0.04,avgopsps=22945.0,bw=0.0,lat=nan,ops=3258462.0,opsps=0.0,threads=1.0 1511776002000000000': invalid number"}

[RUN #1 52%, 155 secs] 1511776015 timestamp:  1 threads:     3353682 ops,       0 (avg:   21635) ops/sec, 0/sec (avg: 89550728/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3353682', 'avgbw': '89550728', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  21635', 'lat': ' -nan'}
400: {"error":"unable to parse 'memtier_stats,hostname=memtiera avgbw=89550728.0,avglat=0.04,avgopsps=21635.0,bw=0.0,lat=nan,ops=3353682.0,opsps=0.0,threads=1.0 1511776015000000000': invalid number"}

[RUN #1 52%, 156 secs] 1511776016 timestamp:  1 threads:     3353682 ops,       0 (avg:   21496) ops/sec, 0/sec (avg: 88976682/sec),  -nan (avg:  0.04) msec latency

{'opsps': '      0', 'ops': '    3353682', 'avgbw': '88976682', 'bw': '0', 'threads': ' 1', 'avglat': ' 0.04', 'avgopsps': '  21496', 'lat': ' -nan'}

**Comment by carverdamien** [comment]
Influxdb does not support nan
https://github.com/influxdata/influxdb/issues/4089
